### ISSUE TITLE
well everything maybe still not working

### ISSUE THREAD

**Issue by mynameismhmd** [SushilKumar8847/Zestik_Cosmetics#1]

**Comment by tibfox** [comment]
@mynameismhmd I have no idea what your problem is because you did not supply any information to this issue.. 

- I cloned this repo
- updated all dependencies
- made some changes following migration gues of the never dependencies

and the package works like a charm... Please try to give developers and visitors some info next time.

**Comment by mynameismhmd** [comment]
well i see lots of errors i cant describe it thats why i said everything i will test it today and see if its still not working

**Comment by tibfox** [comment]
you have to report the errors - that's how this whole issue thing is working here on github ;)

**Comment by mynameismhmd** [comment]
i checked now also alot of errors man im closing this issue just see it for yourself the errors are alot who can fix error one by one like this ba bye sorry cant provide the errors because they are freaking alot
